Update pihole-cloudsync

diff --git a/pihole-cloudsync b/pihole-cloudsync
--- a/pihole-cloudsync
+++ b/pihole-cloudsync
@@ -42,65 +42,65 @@ domain_list='domainlist.csv'
 # Force sudo if not running with root privileges
 SUDO=''
 if [ "$EUID" -ne 0 ]
-  then SUDO='sudo'
+    then SUDO='sudo'
 fi
 
 # FUNCTIONS
 push_initialize () {
 
-	# Go to local Git repo directory
-	cd $personal_git_dir || exit
-
-	# Export Ad and Domain lists from Gravity database
-	$SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
-	$SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
-
-	# Add all lists to local Git repo
-	$SUDO git add .
-	echo "Local Pi-hole initialized in Push mode and local lists were added to local Git repo. Run 'pihole-cloudsync --push' to push to remote Git repo.";
-}
-
-pull_initialize () {
-	# Go to Pi-hole directory, exit if doesn't exist
-	cd $personal_git_dir || exit
-
-	# Update local Git repo from remote Git repo
-	$SUDO git remote update > /dev/null
-
-	# Remove -q option if you don't want to run in "quiet" mode
-	$SUDO git fetch --all -q
-	$SUDO git reset --hard origin/master -q
-
-	# Stop DNS server
-	$SUDO service pihole-FTL stop
-
-	# Overwrite local database tables
-	$SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
-	$SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
-	$SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
-	$SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
-
-	# Restart Pi-hole to pick up changes
-	$SUDO pihole -g
-
-	# Display success messages
-	echo "Local Pi-hole initialized in Pull mode and first pull successfully completed.";
-	echo "Future pulls can now be perfomed with 'pihole-cloudsync --pull'.";
-}
-
-push () {
-
-	# Go to local Git repo directory
+    # Go to local Git repo directory
     cd $personal_git_dir || exit
 
     # Export Ad and Domain lists from Gravity database
     $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
     $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
 
-	# Compare local files to remote Git repo
-	$SUDO git remote update > /dev/null
+    # Add all lists to local Git repo
+    $SUDO git add .
+    echo "Local Pi-hole initialized in Push mode and local lists were added to local Git repo. Run 'pihole-cloudsync --push' to push to remote Git repo.";
+}
 
-	# If local files are different than remote, update remote Git repo
+pull_initialize () {
+    # Go to Pi-hole directory, exit if doesn't exist
+    cd $personal_git_dir || exit
+
+    # Update local Git repo from remote Git repo
+    $SUDO git remote update > /dev/null
+
+    # Remove -q option if you don't want to run in "quiet" mode
+    $SUDO git fetch --all -q
+    $SUDO git reset --hard origin/master -q
+
+    # Stop DNS server
+    $SUDO service pihole-FTL stop
+
+    # Overwrite local database tables
+    $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
+    $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
+    $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
+    $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
+
+    # Restart Pi-hole to pick up changes
+    $SUDO pihole -g
+
+    # Display success messages
+    echo "Local Pi-hole initialized in Pull mode and first pull successfully completed.";
+    echo "Future pulls can now be perfomed with 'pihole-cloudsync --pull'.";
+}
+
+push () {
+
+    # Go to local Git repo directory
+    cd $personal_git_dir || exit
+
+    # Export Ad and Domain lists from Gravity database
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
+
+    # Compare local files to remote Git repo
+    $SUDO git remote update > /dev/null
+
+    # If local files are different than remote, update remote Git repo
     CHANGED=$($SUDO git --work-tree=$personal_git_dir status --porcelain)
     if [ -n "${CHANGED}" ]; then
         echo 'Local Pi-hole lists are different than remote git repo. Updating remote repo...';
@@ -111,30 +111,30 @@ push () {
         echo 'Done!';
         exit 0
     else
-	    # If local files are the same as remote, do nothing and exit
-	    echo 'Remote git repo matches local Pi-hole lists. No further action required.';
-		exit 0
+        # If local files are the same as remote, do nothing and exit
+        echo 'Remote git repo matches local Pi-hole lists. No further action required.';
+        exit 0
     fi
 }
 
 pull () {
         # Go to Pi-hole directory, exit if doesn't exist
-	cd $personal_git_dir || exit
+    cd $personal_git_dir || exit
 
-	# Update local Git repo from remote Git repo
-	$SUDO git remote update > /dev/null
-	CHANGED=$($SUDO git log HEAD..origin/master --oneline)
-	if [ -n "${CHANGED}" ]; then
+    # Update local Git repo from remote Git repo
+    $SUDO git remote update > /dev/null
+    CHANGED=$($SUDO git log HEAD..origin/master --oneline)
+    if [ -n "${CHANGED}" ]; then
         echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
         # Remove -q option if you don't want to run in "quiet" mode
         $SUDO git fetch --all -q
-		$SUDO git reset --hard origin/master -q
+        $SUDO git reset --hard origin/master -q
         $SUDO service pihole-FTL stop
         $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
         $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
         $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
         $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
-		$SUDO pihole -g
+        $SUDO pihole -g
         echo 'Done!';
         exit 0
     else
@@ -170,11 +170,11 @@ do
     # Pull / Download - Pulls updated Pi-hole lists from remote Git repo
     elif [ "$arg" == "--pull" ] || [ "$arg" == "--download" ] || [ "$arg" == "--down" ]|| [ "$arg" == "-d" ]; then
         echo "$arg option detected. Running in Pull/Download mode."
-	    pull
+        pull
         exit 0
     # Help - Displays help dialog
     elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ] || [ "$arg" == "-?" ]; then
-	    cat << EOF
+    cat << EOF
 Usage: pihole-cloudsync <option>
 
 Options:
