Updated pihole-cloudsync to newest version

diff --git a/pihole-cloudsync b/pihole-cloudsync
--- a/pihole-cloudsync
+++ b/pihole-cloudsync
@@ -4,9 +4,11 @@
 # pihole-cloudsync
 # Helper script to keep multiple Pi-holes' lists synchronized via Git
 
-# Version 4.0 - March 28, 2020 - Steve Jenkins (stevejenkins.com)
-version='4.11'
-update='May 15, 2020'
+# Steve Jenkins (stevejenkins.com)
+# https://github.com/stevejenkins/pihole-cloudsync
+
+version='5.1'
+update='6. January 2021'
 
 # SETUP
 # Follow the instructions in the README to set up your own private Git
@@ -30,22 +32,10 @@ update='May 15, 2020'
 # Project Home: https://github.com/stevejenkins/pihole-cloudsync
 ###########################################################################
 # CONSTANTS
-pihole_version=5
 personal_git_dir='/usr/local/bin/my-pihole-lists'
-pihole_dir='/etc/pihole'
-ad_list='adlists.list'
-black_list='black.list'
-blacklist_list='blacklist.txt'
-whitelist_list='whitelist.txt'
-regex_list='regex.list'
-gravity_db='gravity.db'
-custom_list='custom.list'
-###########################################################################
-# FOR SHARED HOSTS MODE ONLY
-# RE-INITIALIZE WITH --initpush OR --initpull AFTER ENABLING THIS MODE
-enable_hosts=off
-local_hosts='/etc/hosts'
-shared_hosts='sharedhosts.txt'
+gravity_db='/etc/pihole/gravity.db'
+ad_list='adlist.csv'
+domain_list='domainlist.csv'
 ###########################################################################
 # SHOULDN'T NEED TO EDIT BELOW THIS LINE
 
@@ -55,123 +45,107 @@ if [ "$EUID" -ne 0 ]
   then SUDO='sudo'
 fi
 
-# Case-insensitive check for Shared Hosts Mode
-shared_hosts_mode=''
-if [ $(echo "$enable_hosts" |tr [:upper:] [:lower:]) == "yes" ] || [ $(echo "$enable_hosts" |tr [:upper:] [:lower:]) == "y" ] || [ $(echo "$enable_hosts" |tr [:upper:] [:lower:]) == "on" ] || [ $(echo "$enable_hosts" |tr [:upper:] [:lower:]) == "true" ] || [ $(echo "$enable_hosts" |tr [:upper:] [:lower:]) == "1" ]; then
-	shared_hosts_mode='1'
-	echo "Shared Hosts Mode ENABLED.";
-else
-	echo "Shared Hosts Mode DISABLED.";
-fi
-
 # FUNCTIONS
 push_initialize () {
-	cd $pihole_dir || exit
-	if [ "$pihole_version" == "5" ]; then
-		$SUDO touch $gravity_db  # $custom_list
-		$SUDO cp $gravity_db $personal_git_dir  # $custom_list 
-	else
-		$SUDO touch $ad_list $black_list $blacklist_list $whitelist_list $regex_list
-		$SUDO cp $ad_list $black_list $blacklist_list $whitelist_list $regex_list $personal_git_dir
-	fi
 
-	if [ "$shared_hosts_mode" ]; then
-		$SUDO sed -n '/# SHARED HOSTS - START/,/# SHARED HOSTS - END/p' $local_hosts | $SUDO sed '1d;$d' > /tmp/$shared_hosts
-		$SUDO cp /tmp/$shared_hosts $personal_git_dir
-	fi
+	# Go to local Git repo directory
 	cd $personal_git_dir || exit
+
+	# Export Ad and Domain lists from Gravity database
+	$SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
+	$SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
+
+	# Add all lists to local Git repo
 	$SUDO git add .
 	echo "Local Pi-hole initialized in Push mode and local lists were added to local Git repo. Run 'pihole-cloudsync --push' to push to remote Git repo.";
 }
+
 pull_initialize () {
+	# Go to Pi-hole directory, exit if doesn't exist
 	cd $personal_git_dir || exit
+
+	# Update local Git repo from remote Git repo
 	$SUDO git remote update > /dev/null
+
 	# Remove -q option if you don't want to run in "quiet" mode
 	$SUDO git fetch --all -q
 	$SUDO git reset --hard origin/master -q
-	if [ "$pihole_version" == "5" ]; then
-		$SUDO service pihole-FTL stop
-		$SUDO cp $gravity_db $pihole_dir  # $custom_list 
-		$SUDO service pihole-FTL start
-	else
-		$SUDO cp $ad_list $black_list $blacklist_list $whitelist_list $regex_list $pihole_dir
-	fi
 
-	if [ "$shared_hosts_mode" ]; then
-		$SUDO cp $local_hosts /tmp/hosts
-		$SUDO sed -e '/# SHARED HOSTS - START/,/# SHARED HOSTS - END/{/^# SHARED HOSTS/!d}' \
-		-e "/# SHARED HOSTS - START.*$/r $shared_hosts" \
-		--in-place=.bak /tmp/hosts
-		$SUDO mv /tmp/hosts $local_hosts
-	fi
+	# Stop DNS server
+	$SUDO service pihole-FTL stop
+
+	# Overwrite local database tables
+	$SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
+	$SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
+	$SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
+	$SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
+
+	# Restart Pi-hole to pick up changes
 	$SUDO pihole -g
+
+	# Display success messages
 	echo "Local Pi-hole initialized in Pull mode and first pull successfully completed.";
 	echo "Future pulls can now be perfomed with 'pihole-cloudsync --pull'.";
 }
-push () {
-	cd $pihole_dir || exit
-        if [ "$pihole_version" == "5" ]; then
-                $SUDO cp $gravity_db $personal_git_dir  # $custom_list 
-	else
-		$SUDO cp $ad_list $black_list $blacklist_list $whitelist_list $regex_list $personal_git_dir
-	fi
 
-	if [ "$shared_hosts_mode" ]; then
-		$SUDO sed -n '/# SHARED HOSTS - START/,/# SHARED HOSTS - END/p' $local_hosts | $SUDO sed '1d;$d' > /tmp/$shared_hosts
-		$SUDO cp /tmp/$shared_hosts $personal_git_dir
-	fi
-	cd $personal_git_dir || exit
+push () {
+
+	# Go to local Git repo directory
+    cd $personal_git_dir || exit
+
+    # Export Ad and Domain lists from Gravity database
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
+
+	# Compare local files to remote Git repo
 	$SUDO git remote update > /dev/null
-        CHANGED=$($SUDO git --work-tree=$personal_git_dir status --porcelain)
-        if [ -n "${CHANGED}" ]; then
-                echo 'Local Pi-hole lists are different than remote Git repo. Updating remote repo...';
-		rightnow=$(date +"%B %e, %Y %l:%M%p")
-		# Remove -q option if you don't want to run in "quiet" mode
-		$SUDO git commit -a -m "Updated $rightnow" -q
-		$SUDO git push -q
-		echo 'Done!';
+
+	# If local files are different than remote, update remote Git repo
+    CHANGED=$($SUDO git --work-tree=$personal_git_dir status --porcelain)
+    if [ -n "${CHANGED}" ]; then
+        echo 'Local Pi-hole lists are different than remote git repo. Updating remote repo...';
+        rightnow=$(date +"%B %e, %Y %l:%M%p")
+        # Remove -q option if you don't want to run in "quiet" mode
+        $SUDO git commit -a -m "Updated $rightnow" -q
+        $SUDO git push -q
+        echo 'Done!';
+        exit 0
+    else
+	    # If local files are the same as remote, do nothing and exit
+	    echo 'Remote git repo matches local Pi-hole lists. No further action required.';
 		exit 0
-        else
-                echo 'Remote Git repo matches local Pi-hole lists. No further action required.';
-		exit 0
-        fi
+    fi
 }
+
 pull () {
+        # Go to Pi-hole directory, exit if doesn't exist
 	cd $personal_git_dir || exit
+
+	# Update local Git repo from remote Git repo
 	$SUDO git remote update > /dev/null
 	CHANGED=$($SUDO git log HEAD..origin/master --oneline)
 	if [ -n "${CHANGED}" ]; then
-                echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
-                # Remove -q option if you don't want to run in "quiet" mode
-                $SUDO git fetch --all -q
+        echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
+        # Remove -q option if you don't want to run in "quiet" mode
+        $SUDO git fetch --all -q
 		$SUDO git reset --hard origin/master -q
-		if [ "$pihole_version" == "5" ]; then
-			$SUDO service pihole-FTL stop
-			$SUDO cp $gravity_db $pihole_dir  # $custom_list 
-			$SUDO service pihole-FTL start
-		else
-			$SUDO cp $ad_list $black_list $blacklist_list $whitelist_list $regex_list $pihole_dir
-		fi
-
-		if [ "$shared_hosts_mode" ]; then
-			$SUDO cp $local_hosts /tmp/hosts
-			$SUDO sed -e '/# SHARED HOSTS - START/,/# SHARED HOSTS - END/{/^# SHARED HOSTS/!d}' \
-			-e "/# SHARED HOSTS - START.*$/r $shared_hosts" \
-			--in-place=.bak /tmp/hosts
-			$SUDO mv /tmp/hosts $local_hosts
-		fi
+        $SUDO service pihole-FTL stop
+        $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
+        $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
+        $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
+        $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
 		$SUDO pihole -g
-                echo 'Done!';
-                exit 0
-        else
-                echo 'Local Pi-hole lists match remote Git repo. No further action required.';
-                exit 0
-        fi
+        echo 'Done!';
+        exit 0
+    else
+        echo 'Local Pi-hole lists match remote git repo. No further action required.';
+        exit 0
+    fi
 }
+
 ###########################################################################
 # Check to see whether a command line option was provided
-if [ -z "$1" ]
-  then
+if [ -z "$1" ]; then
     echo "Missing command line option. Try --push, --pull, or --help."
     exit 1
 fi
@@ -179,33 +153,28 @@ fi
 for arg in "$@"
 do
     # Initialize - adds primary Pi-hole's lists to local Git repo before first push/upload
-    if [ "$arg" == "--initpush" ]
-    then
-	echo "$arg option detected. Initializing local Git repo for Push/Upload.";
-	push_initialize
-	exit 0
+    if [ "$arg" == "--initpush" ]; then
+        echo "$arg option detected. Initializing local Git repo for Push/Upload.";
+        push_initialize
+        exit 0
     # Initialize - adds primary Pi-hole's lists to local Git repo before first push/upload
-    elif [ "$arg" == "--initpull" ]
-    then
-	echo "$arg option detected. Initializing local Git repo for Pull/Download.";
-	pull_initialize
-	exit 0
+    elif [ "$arg" == "--initpull" ]; then
+        echo "$arg option detected. Initializing local Git repo for Pull/Download.";
+        pull_initialize
+        exit 0
     # Push / Upload - Pushes updated local Pi-hole lists to remote Git repo
-    elif [ "$arg" == "--push" ] || [ "$arg" == "--upload" ] || [ "$arg" == "--up" ] || [ "$arg" == "-u" ]
-    then
-	echo "$arg option detected. Running in Push/Upload mode."
-	push
-	exit 0
+    elif [ "$arg" == "--push" ] || [ "$arg" == "--upload" ] || [ "$arg" == "--up" ] || [ "$arg" == "-u" ]; then
+        echo "$arg option detected. Running in Push/Upload mode."
+        push
+        exit 0
     # Pull / Download - Pulls updated Pi-hole lists from remote Git repo
-    elif [ "$arg" == "--pull" ] || [ "$arg" == "--download" ] || [ "$arg" == "--down" ]|| [ "$arg" == "-d" ]
-    then
+    elif [ "$arg" == "--pull" ] || [ "$arg" == "--download" ] || [ "$arg" == "--down" ]|| [ "$arg" == "-d" ]; then
         echo "$arg option detected. Running in Pull/Download mode."
-	pull
+	    pull
         exit 0
     # Help - Displays help dialog
-    elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ] || [ "$arg" == "-?" ]
-    then
-	cat << EOF
+    elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ] || [ "$arg" == "-?" ]; then
+	    cat << EOF
 Usage: pihole-cloudsync <option>
 
 Options:
@@ -224,14 +193,13 @@ Project Home: https://github.com/stevejenkins/pihole-cloudsync
 EOF
 
     # Version - Displays version number
-    elif [ "$arg" == "--version" ] || [ "$arg" == "-v" ]
-	then
-	echo 'pihole-cloudsync v'$version' - Updated '"$update";
-	echo 'https://github.com/stevejenkins/pihole-cloudsync';
+    elif [ "$arg" == "--version" ] || [ "$arg" == "-v" ]; then
+        echo 'pihole-cloudsync v'$version' - Updated '"$update";
+        echo 'https://github.com/stevejenkins/pihole-cloudsync';
 
     # Invalid command line option was passed
     else
-	echo "Invalid command line option. Try --push, --pull, or --help."
-	exit 1
+        echo "Invalid command line option. Try --push, --pull, or --help."
+        exit 1
     fi
 done
